packages/@pollyjs/core/src/-private/response.js, packages/@pollyjs/core/tests/unit/-private/response-test.js
=> feat(core): Default `Response` status code to 200

packages/@pollyjs/core/src/-private/request.js
=> feat(core): Add `json` property to `Request`

README.md
Added helpful links to promote our team!
=> docs: Added credits and links to open positions

README.md
Hi there, thanks for this project, it looks like it could be quite useful!
It took me about 5 minutes to understand what exactly the project did and to confirm my assumptions based on the description in the readme. Once I saw the second code block in the Quick Start, it made sense immediately.
I thought it may be something that could be useful for the readme for other new users.
Ref: https://netflix.github.io/pollyjs/#/quick-start?id=usage
=> Add recording from Quick Start Docs

packages/@pollyjs/core/src/adapters/fetch/index.js, packages/@pollyjs/ember/yarn.lock
=> fix(core): Set `url` on the fetch Response object

.eslintrc.js, build-scripts/rollup.browser.test.config.js, build-scripts/rollup.jest.test.config.js, build-scripts/rollup.node.test.config.js, jest.config.js, package.json, packages/@pollyjs/adapter-fetch/rollup.config.test.js, packages/@pollyjs/adapter-fetch/tests/jest/integration/adapter-test.js, packages/@pollyjs/adapter-xhr/rollup.config.test.js, packages/@pollyjs/adapter-xhr/tests/jest/integration/adapter-test.js, packages/@pollyjs/persister-fs/tests/integration/persister-test.js, testem.js, yarn.lock
Add XHR & Fetch adapter smoke tests to make sure they behave nicely in JSDom.
=> test: Add jest smoke tests

packages/@pollyjs/adapter-puppeteer/src/index.js, packages/@pollyjs/core/package.json, packages/@pollyjs/core/src/-private/request.js, packages/@pollyjs/core/src/server/index.js, packages/@pollyjs/core/src/utils/parse-url.js, packages/@pollyjs/core/tests/unit/utils/remove-host-from-url-test.js, packages/@pollyjs/core/yarn.lock, packages/@pollyjs/utils/src/index.js, tests/integration/adapter-tests.js
=> fix(adapter-puppeteer): Do not intercept CORS preflight requests

packages/@pollyjs/adapter-puppeteer/package.json, packages/@pollyjs/adapter-puppeteer/src/index.js, yarn.lock
Resolves #93 also refactored to avoid mutating the puppeteer object passed in to Polly.
=> fix: Puppeteer 1.7.0 support

tests/helpers/setup-fetch-record.js, tests/helpers/xhr-request.js, tests/integration/adapter-tests.js, tests/middleware.js, tests/recordings/-pollyjs_2160168770/adapter-fetch_162589637/Integration-Fetch-Adapter-Browser_2847373818/should-properly-handle-204-status-code-response_1592697261/recording.har, tests/recordings/-pollyjs_2160168770/adapter-fetch_162589637/Integration-Fetch-Adapter-Node_1202358354/should-properly-handle-204-status-code-response_1592697261/recording.har, tests/recordings/-pollyjs_2160168770/adapter-puppeteer_3356991759/Integration-Puppeteer-Adapter_1203948916/should-be-able-to-abort-from-an-intercept_68559697/recording.har, tests/recordings/-pollyjs_2160168770/adapter-puppeteer_3356991759/Integration-Puppeteer-Adapter_1203948916/should-properly-handle-204-status-code-response_1592697261/recording.har, tests/recordings/-pollyjs_2160168770/adapter-puppeteer_3356991759/Integration-Puppeteer-Adapter_1203948916/should-respect-request-order_2914185093/recording.har, tests/recordings/-pollyjs_2160168770/adapter-xhr_1803529635/Integration-XHR-Adapter_4095563232/should-properly-handle-204-status-code-response_1592697261/recording.har
@cibernox I believe this will cover your change
=> chore: Adds tests to cover #101

packages/@pollyjs/adapter-node-http/src/-private/transport-wrapper.js
=> fix(adapter-node-http): Pause socket on original request

packages/@pollyjs/adapter/src/index.js
=> fix: Test for navigator before accessing

.github/issue_template.md, .github/pull_request_template.md, CONTRIBUTING.md
- Add issue and pull request templates to help us get as much information as possible on the first go
- Update CONTRIBUTING.md to include the requirement of adhering to the conventional commit spec
=> chore: Create github issue and pull request templates

.travis.yml
=> chore: Remove `sudo: false` usage from .travis.yml

docs/test-frameworks/mocha.md
=> docs(core): Add setup docs for ember-mocha

README.md, package.json, yarn.lock
[Rendered](https://github.com/Netflix/pollyjs/pull/235/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
Add a contributor section to the README to pay tribute to everyone who's contributed to the project.
To update in the future:
```sh
yarn contributors
```
=> chore: Adds contributor section to README

CONTRIBUTING.md
This is a quick document change to fix the Lerna link.
Document change.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix: correct Lerna link in contributing.md doc

packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js, packages/@pollyjs/adapter-node-http/tests/integration/adapter-test.js, packages/@pollyjs/adapter-xhr/tests/integration/adapter-test.js, tests/integration/adapter-identifier-tests.js
Partially solves #244 
Puppeteer I'll tackle in a follow up PR.
=> chore: Adds identifier assertions for xhr and fetch adapters

.travis.yml
Also build on Node 12 on Travis.
To test that it builds on Node 12.
=> chore: Build on Node 12

packages/@pollyjs/cli/bin/cli.js
Update all occurrences of `var` with `const`.
=> refactor: minor code refactoring

packages/@pollyjs/adapter-fetch/src/index.js
=> fix(adapter-fetch): Fix "failed to construct Request" issue

packages/@pollyjs/adapter-node-http/package.json, yarn.lock
=> fix(adapter-node-http): Bump nock version to correctly handle responses

.travis.yml, packages/@pollyjs/ember/package.json
Drop support for node 8 as it's EOL.
=> chore: Drop node 8 support

packages/@pollyjs/utils/src/utils/url.js, packages/@pollyjs/utils/tests/unit/utils/url-test.js
This helps differentiated between `?foo` and `?foo=` query params. 
Resolves #301.
=> fix(core): Strict null query param handling

packages/@pollyjs/adapter-node-http/src/index.js
Use requestBodyBuffers to parse body.
Unsure if I need to add/change any tests
See https://github.com/Netflix/pollyjs/pull/303#issuecomment-580103235
=> fix(adapter-node-http): Use requestBodyBuffers to parse body

examples/jest-puppeteer/__recordings__/jest-puppeteer_2726822272/should-be-able-to-navigate-to-all-routes_1130491217/recording.har, examples/jest-puppeteer/__tests__/dummy-app.test.js, examples/jest-puppeteer/jest-puppeteer.config.js, examples/jest-puppeteer/package.json
fixes #290
Pretty sure our other examples need some love also, I'll deal with them in a future PR.
=> test: Updates the jest-puppeteer example

packages/@pollyjs/adapter-node-http/package.json, yarn.lock
Bump nock version to latest.
Resolves #317.
=> fix(adapter-node-http): Bump nock version

docs/server/events-and-middleware.md, packages/@pollyjs/adapter-fetch/src/index.js, packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js, packages/@pollyjs/adapter-node-http/src/index.js, packages/@pollyjs/adapter-node-http/tests/integration/adapter-test.js, packages/@pollyjs/adapter-node-http/tests/utils/get-response-from-request.js, packages/@pollyjs/adapter-xhr/src/index.js, packages/@pollyjs/adapter-xhr/tests/integration/adapter-test.js, packages/@pollyjs/adapter-xhr/tests/utils/xhr-request.js, packages/@pollyjs/adapter/src/index.js, packages/@pollyjs/core/src/-private/request.js, packages/@pollyjs/core/src/server/handler.js
Improve overall abort handling across the adapters.
Resolves #316.
=> fix: Improve abort handling

packages/@pollyjs/adapter/src/index.js, packages/@pollyjs/core/src/-private/container.js, packages/@pollyjs/core/src/polly.js, packages/@pollyjs/core/tests/unit/polly-test.js, packages/@pollyjs/persister/src/index.js, packages/@pollyjs/utils/src/index.js, packages/@pollyjs/utils/src/utils/get-factory-id.js
=> fix: Legacy persisters and adapters should register

docs/node-server/overview.md, packages/@pollyjs/node-server/src/server.js
Add the ability to pass options to the CORS middleware.
Resolves #326.
=> feat(node-server): Pass options to the CORS middleware via `corsOptions`

README.md, packages/@pollyjs/core/README.md
=> chore: Lets -> Let's and tries to improve readability of Why Polly

packages/@pollyjs/adapter-puppeteer/src/index.js
puppeteer remove prependListener after v4.0.0, add it if missing
Resolves https://github.com/Netflix/pollyjs/issues/345
=> fix(adapter-puppeteer): Add prependListener puppeteer@4.0.0 removed

packages/@pollyjs/adapter-fetch/src/index.js, packages/@pollyjs/adapter-node-http/src/index.js, packages/@pollyjs/adapter-node-http/tests/integration/adapter-test.js, packages/@pollyjs/adapter-xhr/src/index.js, packages/@pollyjs/adapter/src/utils/normalize-recorded-response.js, packages/@pollyjs/core/src/-private/request.js, packages/@pollyjs/core/src/-private/response.js, packages/@pollyjs/core/tests/unit/-private/response-test.js, packages/@pollyjs/persister/src/har/response.js, packages/@pollyjs/utils/src/utils/serializers/buffer.js, packages/@pollyjs/utils/tests/node/unit/utils/serializers/buffer.js, tests/integration/persister-tests.js
=> feat!: Use base64 instead of hex encoding for binary data

docs/_sidebar.md, docs/adapters/playwright.md
=> docs: Add documentation for Playwright adapter

docs/configuration.md, docs/quick-start.md, docs/server/request.md, docs/server/route-handler.md, packages/@pollyjs/adapter-fetch/src/index.js, packages/@pollyjs/adapter/src/index.js, packages/@pollyjs/core/package.json, packages/@pollyjs/core/src/-private/logger.js, packages/@pollyjs/core/src/-private/request.js, packages/@pollyjs/core/src/defaults/config.js, packages/@pollyjs/core/src/polly.js, packages/@pollyjs/core/tests/unit/polly-test.js, packages/@pollyjs/core/tests/unit/server/handler-test.js, packages/@pollyjs/core/types.d.ts, packages/@pollyjs/persister/src/index.js, packages/@pollyjs/persister/tests/unit/persister-test.js, yarn.lock
- Replace `logging` option with `logLevel`
- Add more debug logging
=> feat!: Improve logging and add logLevel

docs/configuration.md, packages/@pollyjs/persister/src/index.js, tests/integration/persister-tests.js
=> fix(persister): Only treat status codes >= 400 as failed

packages/@pollyjs/core/tests/unit/utils/normalize-request-test.js, packages/@pollyjs/core/tests/unit/utils/parse-url-test.js, packages/@pollyjs/core/tests/unit/utils/remove-host-from-url-test.js, packages/@pollyjs/utils/package.json, packages/@pollyjs/utils/tests/unit/utils/url-test.js, yarn.lock
Blocked by unshiftio/url-parse#219
=> fix!: Upgrade url-parse

packages/@pollyjs/adapter-fetch/package.json, packages/@pollyjs/adapter-node-http/package.json, packages/@pollyjs/adapter-puppeteer/package.json, packages/@pollyjs/adapter-xhr/package.json, packages/@pollyjs/adapter/package.json, packages/@pollyjs/core/package.json, packages/@pollyjs/node-server/package.json, packages/@pollyjs/persister-fs/package.json, packages/@pollyjs/persister-in-memory/package.json, packages/@pollyjs/persister-local-storage/package.json, packages/@pollyjs/persister-rest/package.json, packages/@pollyjs/persister/package.json, packages/@pollyjs/utils/package.json
Added `types.d.ts` to `package.files` for each package that has `package.types` configured.
`types.d.ts` files were added to each package recently (https://github.com/Netflix/pollyjs/pull/428) but don't get published to npm.
=> fix(types): add types.d.ts to package.files

packages/@pollyjs/adapter/types.d.ts, packages/@pollyjs/core/types.d.ts, packages/@pollyjs/persister/types.d.ts
=> fix(core): Fix types for registering adapters and persisters

CHANGELOG.md
=> docs: Add note about backwards compatibility to changelog

packages/@pollyjs/core/types.d.ts, packages/@pollyjs/persister/package.json, yarn.lock
=> fix: A few more type fixes

packages/@pollyjs/adapter/types.d.ts, packages/@pollyjs/core/types.d.ts, packages/@pollyjs/persister/types.d.ts
the class method types defined currently do not work well when trying to extend a class for a custom adapter and create a lot of typescript errors. this is because some of the types are defined as class properties with anonymous functions rather than actual class methods.
=> fix: Update types for class methods
