docs/persisters/custom.md
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/core/src/persisters/local-storage/index.js
packages/@pollyjs/core/src/persisters/rest/index.js
packages/@pollyjs/core/tests/integration/adapters-test.js
packages/@pollyjs/core/tests/integration/persisters-test.js
packages/@pollyjs/node-server/src/api.js
packages/@pollyjs/node-server/src/express/register-api.js
packages/@pollyjs/persister/README.md
packages/@pollyjs/persister/src/index.js
packages/@pollyjs/persister/tests/unit/persister-test.js

I realized that we don't really need a `findRecordingEntry` method since we fetch the entire recording when persisting anyways. We might as well cache the recording on the first `find` and use that to locally find entries. This should greatly reduce the amount of network requests we make as well as reduce the amount of times we read from disk.
- Cache recordings and bring `findRecordingEntry` into the base persister.
- Bust the cache when saving & deleting.

feat(persister): Cache recordings

---

package.json
packages/@pollyjs/core/src/server/route.js
packages/@pollyjs/core/tests/helpers/file.js
packages/@pollyjs/core/tests/integration/adapters-test.js
packages/@pollyjs/core/tests/unit/utils/serialize-request-body-test.js
test/index.mustache
yarn.lock

This PR does not include the changes to rollup since I consider that separate for Edge support.  IE 11 is a bit more work, but I have most of that done in another branch just need to verify it.
I'll probably introduce a test:legacy command since it's going to slow the build down a bit and make normal debugging in modern browsers difficult.
One of two changes required for #28

chore: Tests now run in MS Edge

---

packages/@pollyjs/core/package.json
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/utils/normalize-request.js
packages/@pollyjs/core/tests/integration/persisters-test.js
packages/@pollyjs/core/tests/unit/utils/normalize-request-test.js
packages/@pollyjs/core/yarn.lock
test/recordings/-pollyjs_2160168770/core_3713949822/Integration-Adapters_529408267/Fetch-Adapter-Rest-Persister_112800326/should-respect-request-order_2914185093/recording.json
test/recordings/-pollyjs_2160168770/core_3713949822/Integration-Adapters_529408267/XHR-Adapter-Rest-Persister_3659812972/should-respect-request-order_2914185093/recording.json

Description of the symptoms of bug and the fix:
1. I run and recorded requests when I my tests in `http://localhost:3000`
2. I then pushed the branch to CI and it failed. It turns out that the recorded requests were not being replayed when ember-cli runs in CI.
3. After some debugging I discovered that the id of the request (the md5 generated from headers, url and method) is different because the normalized URL is different (`/my-url` was being normalized to `http://localhost:7357/my-url`)
The fix is to, on the URL normalization step, if the source url doesn't have a domain, the normalized version should not contain a domain either, effectively keeping the URL relative.
**Warning**: This is a breaking change. Recordings of relative urls that have already been captured will have to be …

fix: If the source URL is relative the normalized must not have domain

---

packages/@pollyjs/node-server/package.json
packages/@pollyjs/node-server/src/server.js
packages/@pollyjs/node-server/yarn.lock

Related to comments in #19 
Address the nuance of having to pass in the testURL as the hostname of the node server.  Now testURL can be anything (other than the default `about:blank`), we recommend `http://localhost` to be the default.

CORs passthrough on node-server

---

.eslintrc.js
docs/node-server/overview.md
package.json
packages/@pollyjs/core/package.json
packages/@pollyjs/core/src/defaults/config.js
packages/@pollyjs/core/src/polly.js
packages/@pollyjs/core/tests/integration/configs.js
packages/@pollyjs/core/tests/unit/polly-test.js
packages/@pollyjs/core/yarn.lock
packages/@pollyjs/ember/addon/-private/preconfigure.js
packages/@pollyjs/ember/index.js
packages/@pollyjs/ember/tests/unit/polly-test.js
packages/@pollyjs/ember/vendor/~preconfigure-polly.js
packages/@pollyjs/node-server/README.md
yarn.lock

- Brings back Polly.configure
- Preconfigure `persisterOptions.host` to `http://localhost:3000` which is the node server default #19 
- Preconfigure ember addon with relative host (empty `host`)

Brings back Polly.configure, Presets persisterOptions.host to the node server default, Preconfigure ember addon

---

docs/server/route-handler.md
packages/@pollyjs/adapter/src/-private/interceptor.js
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/adapter/tests/unit/-private/interceptor-test.js
packages/@pollyjs/core/tests/integration/adapters-test.js
test/recordings/-pollyjs_2160168770/core_3713949822/Integration-Adapters_529408267/Fetch-Adapter-Rest-Persister_112800326/should-be-able-to-abort-from-an-intercept_68559697/recording.har
test/recordings/-pollyjs_2160168770/core_3713949822/Integration-Adapters_529408267/XHR-Adapter-Rest-Persister_3659812972/should-be-able-to-abort-from-an-intercept_68559697/recording.har

Resolves #48.
```js
server
.get('/ping')
.intercept((req, res, interceptor) => interceptor.abort());
server
.get('/pong')
.intercept((req, res, interceptor) => interceptor.passthrough());
```

feat: Abort and passthrough from an intercept

---

README.md
docs/adapters/custom.md
docs/adapters/fetch.md
docs/adapters/xhr.md
docs/api.md
docs/configuration.md
docs/persisters/custom.md
docs/persisters/fs.md
docs/persisters/local-storage.md
docs/persisters/rest.md
docs/quick-start.md
packages/@pollyjs/core/README.md
packages/@pollyjs/core/src/-private/container.js
packages/@pollyjs/core/src/defaults/config.js
packages/@pollyjs/core/src/polly.js
packages/@pollyjs/core/tests/browser/helpers/setup-fetch.js
packages/@pollyjs/core/tests/browser/integration/adapters-test.js
packages/@pollyjs/core/tests/browser/integration/configs.js
packages/@pollyjs/core/tests/browser/integration/persisters-test.js
packages/@pollyjs/core/tests/browser/integration/server-test.js
packages/@pollyjs/core/tests/unit/-private/container-test.js
packages/@pollyjs/core/tests/unit/polly-test.js
packages/@pollyjs/core/tests/unit/test-helpers/mocha-test.js
packages/@pollyjs/ember/addon/-private/preconfigure.js
testem.js

__Adapters__
```js
import { XHRAdapter, FetchAdapter } from '@pollyjs/core';
// Register the xhr adapter so its accessible by all future polly instances
Polly.register(XHRAdapter);
polly.configure({
adapters: ['xhr', FetchAdapter]
});
```
__Persister__
```js
import { LocalStoragePersister, RESTPersister } from '@pollyjs/core';
// Register the local-storage persister so its accessible by all future polly instances
Polly.register(LocalStoragePersister);
polly.configure({
persister: 'local-storage'
});
polly.configure({
persister: RESTPersister
});
```

feat: Improved adapter and persister registration

---

docs/adapters/fetch.md
packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js
packages/@pollyjs/core/src/polly.js

I'll update the docs also.
I can't  apply the same treatment to the XHR adapter since `nise` doesn't enable providing a context object.  I think we spoke about this already, but mentioning again.
Resolves #56

feat: Fetch adapter support for `context` provided via adapterOptions

---

docs/server/request.md
docs/server/response.md
packages/@pollyjs/core/src/-private/http-base.js
packages/@pollyjs/core/src/-private/response.js
packages/@pollyjs/core/tests/unit/-private/http-base-test.js
packages/@pollyjs/core/tests/unit/-private/response-test.js

Resolves #7.
- Move `send`, `json`,  and `type` methods out of `Response` and into `HTTPBase` class
- Add `jsonBody` alias method to `HTTPBase` class.

feat: Move more response methods to shared base class

---

packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/utils/http-headers.js
packages/@pollyjs/core/src/utils/normalize-request.js
packages/@pollyjs/core/src/utils/parse-url.js
packages/@pollyjs/core/tests/unit/utils/parse-url-test.js
testem.js

- Create a shared parseUrl utility that will make sure to match the provided URL string to a url-parse instance
- Support for protocol-relative URLs (Resolves #76)

fix: Improve support for relative URLs

---

packages/@pollyjs/adapter-puppeteer/src/index.js
tests/integration/adapter-tests.js

Resolves #87.
When making a CORS request, Chrome makes a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/preflight_request) to validate that the actual request will be accepted. Since the Puppeteer adapter is making a CORS pass-through request, we also have to intercept the preflight request so it doesnt go through the default adapter's request handler. Without the preflight intercept, the adapter goes into an infinite loop of making preflight requests until the browser crashes.

 fix(adapter-puppeteer): Cors preflight requests

---

packages/@pollyjs/adapter-fetch/src/index.js

It turns out that 204 responses using fetch attempt to call `new Response`
with an empty string as a body, which is illegal and blows hard. The body
must be null.

fix: Allow 204 responses without a body

---

docs/configuration.md
packages/@pollyjs/core/src/defaults/config.js
packages/@pollyjs/persister/src/index.js
tests/integration/persister-tests.js

Currently by default, all new requests are appended to the currently existing recording HAR file. Although this works well (especially when using Polly for an offline only tool), it creates bloated recording files with unused requests. This PR handles the more generic case where a recording file should only contain the requests that have been captured by the running Polly instance. 
_Type_: `Boolean`
_Default_: `false`
When disabled, requests that have not been captured by the running Polly instance will be removed. This ensures that a recording will only contain the requests that were made during the lifespan of the Polly instance. When enabled, new requests will be appended to the recording file.
__Example__
```js
polly.configure({
persisterOptions: {
keepUnusedRequests: true
}
});
```

feat(persister): Add `keepUnusedRequests` config option

---

packages/@pollyjs/adapter-puppeteer/src/index.js

Preflight requests should not be matched to a pollyRequest since Polly should never actually be aware of such a request.

fix: Puppeteer CORS request matching

---

docs/_sidebar.md
docs/test-frameworks/jest-jasmine.md
examples/jest-node-fetch/__recordings__/jest-node-fetch_1142061259/posts_1278140380/should-return-post_148615714/recording.har
examples/jest-node-fetch/__recordings__/jest-node-fetch_1142061259/users_1585235219/should-return-user_4259424139/recording.har
examples/jest-node-fetch/__tests__/index.test.js
examples/jest-node-fetch/package.json
examples/jest-puppeteer/__recordings__/jest-puppeteer_2726822272/should-be-able-to-navigate-to-all-routes_1130491217/recording.har
examples/jest-puppeteer/__tests__/dummy-app.test.js
examples/jest-puppeteer/package.json

@gribnoysup I would love your review on this as well.

docs: Document Jest & Jasmine support using setup-polly-jest

---

packages/@pollyjs/adapter-fetch/package.json
packages/@pollyjs/adapter-puppeteer/package.json
packages/@pollyjs/adapter-xhr/package.json
packages/@pollyjs/adapter/package.json
packages/@pollyjs/cli/package.json
packages/@pollyjs/core/package.json
packages/@pollyjs/node-server/package.json
packages/@pollyjs/persister-fs/package.json
packages/@pollyjs/persister-local-storage/package.json
packages/@pollyjs/persister-rest/package.json
packages/@pollyjs/persister/package.json
packages/@pollyjs/utils/package.json
yarn.lock

- Match package rollup version to root package.json
- Remove unnecessary package dev dependencies
- Bump up some dependencies to latest patch/minor version

chore: Bump package dependencies

---

docs/configuration.md
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/utils/normalize-request.js
packages/@pollyjs/core/tests/unit/utils/normalize-request-test.js
packages/@pollyjs/utils/package.json
tests/integration/adapter-browser-tests.js
yarn.lock

Resolved #136.
Add more fine grain control on how request ids are generated by allowing custom methods to be passed into the `matchRequestsBy` config options.

feat(core): Support custom functions in matchRequestsBy config options

---

examples/jest-node-fetch/__mocks__/node-fetch/index.js
packages/@pollyjs/adapter-fetch/tests/browser/integration/adapter-test.js
packages/@pollyjs/adapter-fetch/tests/common-tests.js
packages/@pollyjs/adapter-fetch/tests/node/integration/adapter-test.js
packages/@pollyjs/core/src/-private/request.js

Make sure we coerce the passed url into a string so we can support Node or Node-like URL objects.

fix(core): Support URL objects

---

packages/@pollyjs/core/src/server/index.js
packages/@pollyjs/core/src/server/middleware.js
packages/@pollyjs/core/src/server/route.js
packages/@pollyjs/core/tests/unit/server/server-test.js

```js
server.get('/ping').on('response', handler1);
server.get('/ping').on('request', handler2);
await fetch('/ping');
```
Given the above code sample, the expected behavior is that `handler1` and `handler2` would both be executed within the lifecycle of the request. The actual result was that only `handler2` was getting executed because the router was overwriting the handler since the routes were the same.

fix(core): Support multiple handlers for same paths

---

packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js
packages/@pollyjs/core/package.json
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/polly.js
packages/@pollyjs/core/src/server/route.js
packages/@pollyjs/core/src/utils/merge-configs.js
packages/@pollyjs/core/tests/unit/utils/merge-configs-test.js
yarn.lock

fix(core): Ignore `context` options from being deep merged

---

packages/@pollyjs/utils/package.json
packages/@pollyjs/utils/src/index.js
packages/@pollyjs/utils/src/utils/build-url.js
packages/@pollyjs/utils/src/utils/url.js
packages/@pollyjs/utils/tests/unit/utils/url-test.js
yarn.lock

Resolves #147.
Adds support for parsing arrays and nested objects in querystrings. To preserve the original querystring structure, I've added logic to determine the original array format used (if any).
The used `qs` library provides an option to specify the `arrayFormat` when stringifying:
```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c'
```

fix(utils): Support arrays & nested objects in query params

---

docs/adapters/custom.md
packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-puppeteer/src/index.js
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/adapter/src/index.js

This is a proof of concept for a simplified `Adapter` class that should make it easier to implement existing and custom adapters. I’d like to get feedback on this proposal and continue working on it if it looks good.
The motivation behind this is to make it easier to implement custom adapters. This is something I struggled with when trying to write an adapter that integrates with Cypress. The documentation on how to write custom adapters is sparse so I had to dig into the code.
1. The number of methods one needs to implement is quite large. (`onConnect`, `onDisconnect`, `onIntercept`, `onPassthrough`, `onRecord`, `onReplay`)
2. One needs to include code to persist the request in `onRecord`. If the implementer forgets this, recording will not work.
3. One needs to manually call …

Simplify adapter implementation

---

.travis.yml
build-scripts/rollup.node.config.js
tests/integration/adapter-tests.js

Node 6 is coming to EOL on April 2019 and our build is already failing due to dependencies dropping support for it as well. To allow simpler implementations on the Node side of Polly, I believe we should drop support of Node 6 as well as it will no longer be maintained in ~3 months.

chore: Remove support for Node 6

---

packages/@pollyjs/adapter/src/index.js

These three fields are referenced in the _identify function.
Fixes #114

fix(adapter): Log information if request couldn't be found in recording

---

docs/server/request.md
docs/server/response.md
packages/@pollyjs/core/src/-private/http-base.js
packages/@pollyjs/core/src/utils/http-headers.js
packages/@pollyjs/core/tests/unit/-private/http-base-test.js
packages/@pollyjs/core/tests/unit/utils/http-headers-test.js

1. Add `removeHeader` and `removeHeaders` API. This is a lot more intuitive than `setHeader('Content-Type', null).
2. Support setting empty header values as the `Host` header can be an empty string.
3. Support for deleting a header property via `delete header[prop]` where prop can be any case.

feat(core): Add removeHeader, removeHeaders, and allow empty headers

---

docs/server/route-handler.md

'overridden' instead of 'overriden'.

Fix Typo in doc

---

docs/server/events-and-middleware.md
packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-node-http/tests/utils/get-response-from-request.js
packages/@pollyjs/adapter-puppeteer/src/index.js
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/adapter-xhr/tests/utils/xhr-request.js
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/adapter/src/utils/stringify-request.js
packages/@pollyjs/core/src/-private/logger.js
packages/@pollyjs/core/src/server/handler.js
tests/integration/adapter-tests.js

Resolves #181 
```js
server.any().on('error', (req, error) => {
console.error(error);
process.exit(1);
});
```

feat: Add `error` event and improve error handling

---

docs/server/route-handler.md
packages/@pollyjs/adapter-fetch/tests/integration/server-test.js
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/server/handler.js
packages/@pollyjs/core/src/server/route.js
tests/helpers/setup-fetch-record.js

Filter requests matched by the route handler with a predicate callback function.
The callback will receive the request as an argument. Return `true` to match the request, `false` otherwise.
Multiple filters can be chained together. They must all return `true` for the route handler to match the given request.
This can be useful when trying to match a request by a part of the url (e.g. a query param), a header,
and/or parts of the request body.

feat(core): Filter requests matched by a route handler

---

packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js

Correctly handle key/value pairs passed as headers to a fetch request.
Resolves #190.
A fetch request can receive headers in the following format: `[['key1', 'value1'], ['key2', 'value2']]`. To be able to support this format as well as any other formats, we create a new [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance with the original headers and serialize that. This allows us to have a normalized interface to interact with.

fix(adapter-fetch): Correctly handle key/value pairs headers

---

CONTRIBUTING.md
docs/adapters/puppeteer.md
packages/@pollyjs/adapter-puppeteer/README.md
packages/@pollyjs/adapter-puppeteer/src/index.js
testem.js

There was a change in Puppeteer 1.7 that forced us to start capturing `"other"` network requests.  
This led to proxying requests for requests like favicons.  This isn't optimal and thankfully is no longer needed as of Puppeteer >= 1.9.
fixes #149

fix(adapter-puppeteer): Remove other resource type matching

---

docs/_sidebar.md
docs/assets/styles.css
docs/server/event.md
docs/server/events-and-middleware.md
docs/server/request.md
docs/server/route-handler.md
packages/@pollyjs/adapter-fetch/tests/integration/server-test.js
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/core/src/-private/event-emitter.js
packages/@pollyjs/core/src/-private/event.js
packages/@pollyjs/core/src/-private/interceptor.js
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/server/handler.js
packages/@pollyjs/core/src/server/interceptor.js
packages/@pollyjs/core/src/server/route.js
packages/@pollyjs/core/src/utils/cancel-fn-after-n-times.js
packages/@pollyjs/core/src/utils/validators.js
packages/@pollyjs/core/tests/unit/-private/event-emitter-test.js
packages/@pollyjs/core/tests/unit/-private/event-test.js
packages/@pollyjs/core/tests/unit/-private/interceptor-test.js
packages/@pollyjs/core/tests/unit/server/handler-test.js
packages/@pollyjs/core/tests/unit/server/interceptor-test.js

This PR includes 2 features that when used together, can be really powerful. 
The first is the ability to remove an intercept or event handler after a specified amount of times it has been called via the handler's `.times(n)` API or by providing it as an option to `.on(eventName, fn, { times })` or `.intercept(fn, { times })`.
The second, is the ability to prevent calling the next handlers registered for the events or intercept. This can be done via `interceptor.stopPropagation()` or via a new Event instance passed to every event handler by calling `event.stopPropagation()`.
Lets take an example where we might want to intercept a user being removed. The first call to GET the user should return the user's info but after we delete the user, it should return a 404.
```js
// First call should …
```

feat(core): Improved control flow with `times` and `stopPropagation`

---

packages/@pollyjs/core/src/test-helpers/lib.js
packages/@pollyjs/core/tests/unit/test-helpers/mocha-test.js

Removing since it mangles the output in a very unexpected way - note the `_context.stop()` ends up within `beforeEach`.

chore(core): Remove unnecessary async fn

---

docs/adapters/xhr.md
packages/@pollyjs/adapter-xhr/package.json
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/adapter-xhr/tests/integration/adapter-test.js
yarn.lock

Add support for mocking the XHR global on a given context (like we currently support with the fetch adapter).
```js
{
adapterOptions: { 
xhr: { context: win }
}
}
```
Resolves #204.

feat(adapter-xhr): Support `context` option

---

docs/quick-start.md

Rewriting of the "Using Polly in the Browser?" section.
Just to improve clarity. See #219 for further details.
Just documentation
BTW, I've been surprised a couple of times by the pre-commit hook not saving my commit message on hook failure. I don't know what the solution is, but it'd be good to either know that the commit message won't necessarily be saved (and so need to be written again), or that something like a pre-push hook be used so the commit message is always available.

chore(core): Improve "...in the Browser?" docs

---

docs/configuration.md
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/core/src/defaults/config.js
packages/@pollyjs/core/src/utils/merge-configs.js
packages/@pollyjs/utils/src/constants/expiry-strategies.js
packages/@pollyjs/utils/src/index.js
tests/integration/adapter-tests.js

Per discussion in #226, this implements an `expiryStrategy` config option and deprecates `recordIfExpired` (without a breaking change) . It supports the existing flows and adds the new `error` state, which throws when the strategy is set to `error` and an expired recording is about to be used in `replay` mode.
We are still implementing tests, but would love input on the approach.
See #226 for detailed info.

 feat: Implement expiryStrategy

---

packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-fetch/tests/integration/server-test.js
packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-puppeteer/tests/unit/adapter-test.js
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/core/src/-private/event-emitter.js
packages/@pollyjs/core/src/-private/logger.js
packages/@pollyjs/core/src/test-helpers/lib.js
packages/@pollyjs/core/tests/unit/-private/container-test.js
packages/@pollyjs/core/tests/unit/-private/event-emitter-test.js
packages/@pollyjs/core/tests/unit/-private/event-test.js
packages/@pollyjs/core/tests/unit/-private/response-test.js
packages/@pollyjs/core/tests/unit/polly-test.js
packages/@pollyjs/utils/src/index.js
packages/@pollyjs/utils/src/utils/assert.js
packages/@pollyjs/utils/src/utils/polly-error.js
packages/@pollyjs/utils/tests/unit/utils/assert-test.js
packages/@pollyjs/utils/tests/unit/utils/polly-error-test.js

- Replace all error usage with a custom `PollyError` class
- Always log errors and default the console group to be open so they are visible
- Improve the base adapter's error handling to give adapters more control
- Refactor some error handling logic to support the above point in some adapters.

feat: PollyError and improved adapter error handling

---

packages/@pollyjs/persister/src/har/log.js

Bowser throws when userAgent is not a string. Default userAgent to empty string when it's empty fixes the issue.
This is to prevent non-browser app (React Native) from crashing.

fix: Default to empty string if userAgent is empty

---

packages/@pollyjs/persister/src/har/log.js

It turns out that Bower doesn't allow any forms of empty UserAgent in getParser function https://github.com/lancedikson/bowser/blob/41bbfc1600fc38d3ea5f49dcfba5bc28cd7357aa/src/parser.js#L24.
Making it works for React Native app.

fix: Bowser.getParser empty string UserAgent error

---

packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js
tests/integration/adapter-tests.js

Correctly handle passing a Request instance to fetch. 
```js
fetch(new Request('/api/foo', { method: 'POST' }), { body: 'bar' });
```
Resolves #255.
The approach taken to solve for this is by patching the global Request class and storing the passed in `url` and `options`. This allows us to not only have direct access to the passed in body (e.g. no need to re-read it off the Request instance) but also not needing to hardcode which properties to take off the instance.

fix(adapter-fetch): Correctly handle Request instance passed into fetch

---

docs/configuration.md
docs/frameworks/ember-cli.md
docs/node-server/overview.md
docs/persisters/rest.md
packages/@pollyjs/ember/.npmignore
packages/@pollyjs/ember/README.md
packages/@pollyjs/ember/blueprints/@pollyjs/ember/files/config/polly.js
packages/@pollyjs/ember/blueprints/@pollyjs/ember/index.js
packages/@pollyjs/ember/config/polly.js
packages/@pollyjs/ember/index.js
packages/@pollyjs/ember/package.json
packages/@pollyjs/node-server/README.md
packages/@pollyjs/node-server/src/config.js

Currently we rely on `included()` to be called and read all config options from `app.options` derived from `ember-cli-build.js` at the time the app is built.  This strategy is no longer reliable since you can run tests against previously built assets which means `included` is never called nor is `app.options` available since the app isn't being built.
Instead, I introduced `config/polly.js` and rely upon my own function to determine what the env is (see: https://github.com/ember-cli/ember-cli/issues/8922 as to why I had to go with that approach).
This is a breaking change for @pollyjs/ember so we'll need to release a new major for the addon.
Resolves #276

fix(ember): BREAKING load polly config for ember by its own module

---

.travis.yml
docs/api.md
packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js
packages/@pollyjs/adapter-puppeteer/tests/integration/adapter-test.js
packages/@pollyjs/core/src/polly.js
packages/@pollyjs/core/tests/unit/polly-test.js
tests/integration/adapter-polly-tests.js

Calling `polly.pause()` will now disconnect from all connected adapters instead of setting the mode to passthrough. Calling `polly.play()` will reconnect to the disconnected adapters before pause was called.
Resolves #285.

fix(core): Disconnect from all adapters when `pause` is called

---

docs/configuration.md
packages/@pollyjs/core/src/utils/merge-configs.js
tests/integration/adapter-tests.js

The `recordIfExpired` option has been expired for a while now and since we're about to release a new major version, this is a good time to remove it altogether.

feat(core): Remove deprecated `recordIfExpired` option

---

packages/@pollyjs/adapter/src/index.js
tests/integration/adapter-tests.js

Clone the recording entry before the `beforeReplay` event so any changes will not actually persist to the stored recording.
Resolves #265.

fix(adapter): Clone the recording entry before mutating it

---

README.md

The link to the "team page" is broken https://jobs.netflix.com/teams/client-applications
it seems that the new link is https://jobs.netflix.com/teams/client-and-ui-engineering
I checked the Netflix jobs site for the correct link to the Client / UI team
The link to the team page at the Netflix jobs subdomain was giving 404

docs: Team page link fix

---

packages/@pollyjs/ember/index.js

`this.root` points to the addon's location within `node_modules` - not the project root.
Since we cannot bank on `this.project` to always be available to find the project root folder (see: #276) we have to use the current working directory of the process to determine the root directory of the project - which Ember also seems to use internally.
Fixes #297

fix(ember): Config read from project root

---

docs/adapters/custom.md
docs/persisters/custom.md
packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-puppeteer/src/index.js
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/adapter/README.md
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/core/README.md
packages/@pollyjs/core/src/-private/container.js
packages/@pollyjs/core/src/polly.js
packages/@pollyjs/core/tests/unit/-private/container-test.js
packages/@pollyjs/core/tests/unit/polly-test.js
packages/@pollyjs/persister-fs/src/index.js
packages/@pollyjs/persister-fs/tests/unit/persister-test.js
packages/@pollyjs/persister-in-memory/src/index.js
packages/@pollyjs/persister-local-storage/src/index.js
packages/@pollyjs/persister-rest/src/index.js
packages/@pollyjs/persister/README.md
packages/@pollyjs/persister/src/index.js
packages/@pollyjs/persister/tests/unit/persister-test.js
tests/helpers/setup-fetch-record.js
tests/integration/adapter-tests.js
tests/integration/persister-tests.js

Done in a backwards compatible way.  In the next major we can remove the deprecations.
Fixes #309

Deprecates adapter & persister `name` in favor of `id`

---

docs/configuration.md
packages/@pollyjs/core/src/defaults/config.js
packages/@pollyjs/persister/src/har/log.js
packages/@pollyjs/persister/src/index.js
packages/@pollyjs/persister/tests/unit/har-test.js
tests/integration/persister-tests.js

When disabled, entries in the the final HAR will be sorted by the request's timestamp.
This is done by default to satisfy the HAR 1.2 spec but can be enabled to improve
diff readability when committing recordings to git.
Related to #269.

feat(persister): Add `disableSortingHarEntries` option

---

packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-node-http/tests/integration/adapter-test.js
packages/@pollyjs/adapter/src/utils/normalize-recorded-response.js
packages/@pollyjs/core/src/-private/request.js
packages/@pollyjs/core/src/-private/response.js
packages/@pollyjs/core/tests/unit/-private/response-test.js
packages/@pollyjs/persister/src/har/response.js
tests/integration/persister-tests.js

The core issue was in `getChunksFromBody` where we pass it the recorded body and response headers. Since the body is a string, it can't really know if the original buffer was binary or not. To get around that, we now store whether the response content is binary or not in the HAR file and expose it via the response class.
Resolves #327.

fix(adapter-node-http): Improve binary response body handling

---

packages/@pollyjs/core/src/-private/request.js
tests/integration/adapter-tests.js

Compute the request's order based on its id as well as the recording id it will be accessed from.
Resolves #340.

fix(core): Compute order based on id and recording name

---

docs/adapters/custom.md
packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-fetch/tests/integration/adapter-test.js
packages/@pollyjs/adapter-fetch/tests/integration/server-test.js

Adds the property `statusText` to the response returned by `fetch`.
The `Response` object created by the `fetch-adapter` may return more info, this could be useful to simulare a real request to the server.

fix(adapter-fetch): Add statusText to the response

---

docs/server/route-handler.md

[Online doc](https://netflix.github.io/pollyjs/#/server/route-handler?id=stoppropagation)
In above link , the example usage of interceptor.stopPropagation has typo 
It mocking `/session/:id` but fetching `/users/:id`
Fix the typo and make the example work

docs: Typo in interceptor.stopPropagation

---

packages/@pollyjs/adapter-xhr/src/index.js

Modifying the `responseType` for synchronous requests is not allowed. Since we really just need to override `blob` or `arraybuffer` to `arraybuffer` and not default it to `text`, I moved the logic into an if statement which should naturally add support back to synchronous requests.
Resolves #356.

fix(adapter-xhr): Only modify the `responseType` if it was changed

---

packages/@pollyjs/adapter-node-http/src/index.js

Fixes a memory leak with Jest due to native module monkey patching. More details in the issue I filed [here](https://github.com/Netflix/pollyjs/issues/370). Note that I did not add any tests; implementing tests to assert the existence of a memory leak is not simple, but the changes here are. This is easily demonstrated in any jest test suite using polly with the node-http adapter by running the following command:
```
jest --coverage --verbose --colors --logHeapUsage --runInBand --detectLeaks
```
Memory leaks are bad :)

fix(adapter-node-http): Remove module monkey patching on disconnect

---

docs/server/request.md
packages/@pollyjs/core/src/-private/request.js

Add `overrideRecordingName` and `configure` methods to Request public API.
Resolved #365.

feat(core): Add `overrideRecordingName` and `configure` to public API

---

packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/utils/src/index.js
packages/@pollyjs/utils/src/utils/clone-arraybuffer.js

When context is provided to both the XHR and Fetch adapters, the arraybuffers that are created by the responses don't pass Buffer.from's instanceof check. To get around that (for now), we clone the ArrayBuffer which uses the same constructor that Buffer.from expects.
Resolves #388.

fix: Handle failed arraybuffer instanceof checks

---

packages/@pollyjs/ember/package.json
yarn.lock

Resolves this deprecation with ember 3.27+:
> DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.
> 
> See https://deprecations.emberjs.com/v3.x/#toc_ember-global for details.
>
> Usages of the Ember Global may be caused by an outdated ember-cli-babel dependency. The following steps may help:
>
> - Upgrade the following addons to the latest version:
>   - @pollyjs/ember

feat(ember): Upgrade ember-cli-babel to ^7.26.6

---

docs/adapters/custom.md
docs/persisters/custom.md
packages/@pollyjs/adapter-fetch/src/index.js
packages/@pollyjs/adapter-node-http/src/index.js
packages/@pollyjs/adapter-node-http/tests/jest/integration/fetch-test.js
packages/@pollyjs/adapter-node-http/tests/jest/integration/xhr-test.js
packages/@pollyjs/adapter-puppeteer/src/index.js
packages/@pollyjs/adapter-xhr/src/index.js
packages/@pollyjs/adapter/src/index.js
packages/@pollyjs/adapter/types.d.ts
packages/@pollyjs/core/src/-private/logger.js
packages/@pollyjs/core/types.d.ts
packages/@pollyjs/persister-fs/src/index.js
packages/@pollyjs/persister-fs/tests/unit/persister-test.js
packages/@pollyjs/persister-in-memory/src/index.js
packages/@pollyjs/persister-local-storage/src/index.js
packages/@pollyjs/persister-rest/src/index.js
packages/@pollyjs/persister/README.md
packages/@pollyjs/persister/src/index.js
packages/@pollyjs/persister/tests/unit/persister-test.js
packages/@pollyjs/persister/types.d.ts
tests/helpers/setup-persister.js
tests/integration/adapter-tests.js
tests/integration/persister-tests.js

- Adapter
- `passthroughRequest` renamed to `onFetchResponse`
- `respondToRequest` renamed to `onRespond`
- Persister
- `findRecording` renamed to `onFindRecording`
- `saveRecording` renamed to `onSaveRecording`
- `deleteRecording` renamed to `onDeleteRecording`

feat!: Cleanup adapter and persister APIs

---

packages/@pollyjs/persister/types.d.ts

Fix typo in `HarEntry` type declaration. In reality, [the property is called `request`](https://github.com/Netflix/pollyjs/blob/18262cf3213d3f3ca7a778a574c162dc2318860a/packages/%40pollyjs/persister/src/har/entry.js#L18) but the declaration uses `requests` instead.
See above.
In addition to this fix, the declaration is also lacking the `_recordingName` and `creator` properties for `HarLog` instances, but I'm not sure how to best handle these as they are added by the base persister implementation, so it could be possible that a custom persister omits these properties. Perhaps the `HarLog` declaration should be made generic to handle this? Happy to add it to this PR in case that's desired.

fix(persister): `requests` -> `request` in `HarEntry` declaration
